/**
 * `kash docs` — emit the entire CLI command tree as machine-readable
 * JSON.
 *
 * AI agents call this once at startup to discover every command,
 * argument, option, and example without scraping `--help` text. The
 * shape is documented as SemVer-stable: adding new fields is a minor
 * bump, removing them a major bump.
 *
 * Human mode prints a compact summary; JSON mode emits the full tree.
 */

import { Command, type Option } from 'commander';

import { readGlobals } from '../utils/global-options.js';
import { print, printJson, style } from '../utils/output.js';

export type CliDocsOption = {
  /** Raw flag spec as commander stores it (e.g. `--timeout-ms, --timeout <ms>`). */
  readonly flags: string;
  /** Canonical long name (e.g. `--timeout`). May be undefined for short-only flags. */
  readonly long: string | undefined;
  /** Short flag (e.g. `-l`). May be undefined for long-only flags. */
  readonly short: string | undefined;
  /**
   * Alternative flag names accepted at parse time, separate from
   * `long` and `short`. Populated when the option declares multiple
   * spellings (e.g. `--timeout-ms, --timeout`). Agents that emit
   * shell completions or generate documentation should treat every
   * entry as equivalent to `long`/`short`.
   */
  readonly aliases: readonly string[];
  readonly description: string;
  readonly required: boolean;
  readonly optional: boolean;
  readonly defaultValue: unknown;
  readonly choices: readonly string[] | undefined;
};

export type CliDocsArgument = {
  readonly name: string;
  readonly required: boolean;
  readonly variadic: boolean;
  readonly description: string;
};

export type CliDocsCommand = {
  readonly name: string;
  readonly fullName: string;
  readonly description: string;
  readonly aliases: readonly string[];
  readonly arguments: readonly CliDocsArgument[];
  readonly options: readonly CliDocsOption[];
  readonly subcommands: readonly CliDocsCommand[];
};

/**
 * Walk a Commander program and produce the JSON tree. Recursive over
 * sub-commands.
 */
export function describeCommand(cmd: Command, parents: readonly string[] = []): CliDocsCommand {
  const name = cmd.name();
  const fullName = [...parents, name].join(' ');

  return {
    name,
    fullName,
    description: cmd.description(),
    aliases: cmd.aliases(),
    arguments: cmd.registeredArguments.map(
      (arg): CliDocsArgument => ({
        name: arg.name(),
        required: arg.required,
        variadic: arg.variadic,
        description: arg.description,
      })
    ),
    // `--help` and `-V/--version` are autogenerated by Commander on
    // every command; they are not part of the contract any agent
    // should plan calls against. Filter them so the docs tree only
    // surfaces real options.
    options: cmd.options
      .filter((opt) => opt.long !== '--help' && opt.long !== '--version')
      .map((opt) => describeOption(opt)),
    subcommands: cmd.commands
      .filter((c) => !isHelpCommand(c))
      .map((c) => describeCommand(c, [...parents, name])),
  };
}

/**
 * Detect Commander's autogenerated `help [command]` subcommand. We
 * filter it out so `kash docs --json` only describes real commands.
 *
 * Commander stores a `_helpCommand` reference on the parent and
 * always names the autogenerated command `help` — we check both: the
 * structural `_helpCommand` reference is the primary signal (resilient
 * to Commander renaming the default), the name fallback covers
 * versions where the structural property isn't exposed.
 */
function isHelpCommand(cmd: Command): boolean {
  // Commander 13's internal field carries the parent's help-command
  // reference. Cast through `unknown` so we don't depend on the
  // private surface in production types — this is a documented
  // structural escape hatch, not arbitrary `any` use.
  const parent = (cmd as unknown as { parent?: { _helpCommand?: Command } }).parent;
  if (parent?._helpCommand === cmd) return true;
  return cmd.name() === 'help';
}

function describeOption(opt: Option): CliDocsOption {
  return {
    flags: opt.flags,
    long: opt.long ?? undefined,
    short: opt.short ?? undefined,
    aliases: extractAliases(opt),
    description: opt.description,
    required: opt.required,
    optional: opt.optional,
    defaultValue: opt.defaultValue ?? null,
    choices: opt.argChoices ?? undefined,
  };
}

/**
 * Derive flag-name aliases from Commander's raw `flags` string.
 *
 * Commander's `Option.flags` is the verbatim spec the call site
 * passed (e.g. `--timeout-ms, --timeout <ms>`). It surfaces `long`
 * and `short` for the first two names, but if the option declares
 * three or more spellings — or two longs as in our `--timeout-ms,
 * --timeout` aliasing — the extras are silently absorbed. We parse
 * the raw spec, dedupe against `long` / `short`, and return whatever
 * else accepts the same value.
 *
 * Agents generating completions or documentation can iterate
 * `[long, short, ...aliases].filter(Boolean)` for the full set of
 * accepted spellings.
 */
function extractAliases(opt: Option): readonly string[] {
  const seen = new Set<string>();
  const known = new Set<string>();
  if (opt.long) known.add(opt.long);
  if (opt.short) known.add(opt.short);
  // The flag-spec string looks like `-l, --limit <n>` or
  // `--timeout-ms, --timeout <ms>` — split on commas, then strip
  // any trailing `<value>`/`[value]` placeholder from each piece.
  for (const raw of opt.flags.split(',')) {
    const piece = raw.trim().split(/\s+/)[0];
    if (piece === undefined || piece.length === 0) continue;
    if (!piece.startsWith('-')) continue; // not a flag (would be the value placeholder)
    if (known.has(piece) || seen.has(piece)) continue;
    seen.add(piece);
  }
  return [...seen];
}

export function buildDocsCommand(getProgram: () => Command): Command {
  return new Command('docs')
    .description('Emit the full command tree as JSON (or summary in human mode).')
    .addHelpText(
      'after',
      `
Examples:
  $ kash docs                              # human summary tree
  $ kash docs --json                       # full machine-readable tree
  $ kash docs --json | jq '.subcommands[].name'
`
    )
    .action((_opts, cmd: Command) => {
      const globals = readGlobals(cmd);
      const tree = describeCommand(getProgram());

      if (globals.json) {
        printJson(tree);
        return;
      }

      print('');
      print(style.bold(`${tree.fullName} — ${tree.description}`));
      printSubtree(tree, '');
    });
}

function printSubtree(node: CliDocsCommand, indent: string): void {
  for (const sub of node.subcommands) {
    print(`${indent}  ${style.cyan(sub.name)}  ${style.dim(sub.description)}`);
    printSubtree(sub, `${indent}  `);
  }
}
