/**
 * Build-time bundler — reads every `docs/api-errors/<CODE>.md` page in
 * the monorepo and emits `src/api-error-bundle.generated.ts` with a
 * `Record<string, string>` mapping each ErrorCode to its full markdown
 * body.
 *
 * Why bundle at build time (not read at runtime): the CLI is published
 * to npm as a self-contained package — it can't reach back into the
 * monorepo's `docs/` tree from a globally-installed binary. Bundling
 * means `kash explain MARKET_NOT_TRADEABLE` works offline, anywhere,
 * with the same content the GitHub-hosted docs page shows.
 *
 * Run as a tsup `prebuild` step (see package.json scripts). The output
 * file is `.generated.ts` so it's git-ignored AND obvious-by-name that
 * editing it by hand is wrong.
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DOCS_DIR = resolve(__dirname, '../../../docs/api-errors');
const OUT_PATH = resolve(__dirname, '../src/api-error-bundle.generated.ts');

type Bundle = Record<string, string>;

function loadBundle(): Bundle {
  const out: Bundle = {};
  const files = readdirSync(DOCS_DIR).filter((f) => f.endsWith('.md') && f !== 'README.md');
  for (const file of files) {
    const code = file.replace(/\.md$/, '');
    const body = readFileSync(join(DOCS_DIR, file), 'utf8');
    out[code] = body;
  }
  return out;
}

function emit(bundle: Bundle): string {
  const entries = Object.keys(bundle)
    .sort()
    .map((code) => {
      // JSON.stringify handles every escape (newlines, quotes, unicode).
      // Falls back to a string literal — no template-literal traps.
      return `  ${JSON.stringify(code)}: ${JSON.stringify(bundle[code] ?? '')},`;
    })
    .join('\n');
  return `/**
 * AUTO-GENERATED by scripts/build-api-error-bundle.ts. DO NOT EDIT.
 *
 * Per-code markdown bodies extracted from docs/api-errors/<CODE>.md at
 * build time so \`kash explain <CODE>\` can render the full docs page
 * offline. Re-run \`pnpm gen:api-error-bundle\` (or \`pnpm build\`,
 * which runs it as a prebuild step) to refresh.
 *
 * Generated at ${new Date().toISOString()}; ${Object.keys(bundle).length} codes covered.
 */

export const API_ERROR_DOCS: Readonly<Record<string, string>> = Object.freeze({
${entries}
});

export type ApiErrorCode = keyof typeof API_ERROR_DOCS;
`;
}

const bundle = loadBundle();
writeFileSync(OUT_PATH, emit(bundle), { encoding: 'utf8' });
console.log(`Wrote ${OUT_PATH} — ${Object.keys(bundle).length} codes`);
