/**
 * Smoke tests for the build-time API error bundle.
 *
 * The bundle is generated by scripts/build-api-error-bundle.ts from
 * docs/api-errors/<CODE>.md at every build / typecheck / test run.
 * These tests verify:
 *
 *   - The expected codes are present (35 today, matching the server's
 *     ERROR_CODES catalog).
 *   - Each entry's body looks like a real markdown page (has a heading
 *     and is non-trivially long), not a placeholder.
 *   - The bundle stays in sync with the docs source-of-truth.
 *
 * Drift here usually means someone added a new ErrorCode in the public-
 * api but forgot to ship a docs/api-errors/<NEW_CODE>.md page, or
 * removed a docs page without removing the corresponding code. Both
 * surface here at PR time.
 */

import { readdirSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import { API_ERROR_DOCS } from '../../src/api-error-bundle.generated.js';

const DOCS_DIR = resolve(__dirname, '../../../../docs/api-errors');

describe('api-error-bundle.generated.ts', () => {
  it('every code in the bundle has a non-trivial markdown body', () => {
    const empty: string[] = [];
    for (const [code, body] of Object.entries(API_ERROR_DOCS)) {
      // A real page starts with `# CODE` and is at least ~200 chars
      // (anything shorter would be a placeholder).
      if (!body.startsWith('# `') || body.length < 200) empty.push(code);
    }
    expect(empty, `placeholder/invalid bodies: ${empty.join(', ')}`).toEqual([]);
  });

  it('bundle covers every docs/api-errors/<CODE>.md page on disk', () => {
    const onDisk = readdirSync(DOCS_DIR)
      .filter((f) => f.endsWith('.md') && f !== 'README.md')
      .map((f) => f.replace(/\.md$/, ''));
    const inBundle = new Set(Object.keys(API_ERROR_DOCS));
    const missing = onDisk.filter((code) => !inBundle.has(code));
    expect(missing, `docs pages on disk missing from bundle: ${missing.join(', ')}`).toEqual([]);
  });

  it('a representative server-side code is reachable via the bundle', () => {
    // MARKET_NOT_TRADEABLE was the canonical example in the user-facing
    // gap discussion — verify it round-trips. Using a known-stable code
    // rather than asserting on the full set so this test doesn't break
    // when new codes are added.
    expect(API_ERROR_DOCS['MARKET_NOT_TRADEABLE']).toBeDefined();
    expect(API_ERROR_DOCS['MARKET_NOT_TRADEABLE']).toMatch(/^# `MARKET_NOT_TRADEABLE`/);
  });
});
